const TRANSLATIONS = {
  en: {
    nav: {
      home: 'Home',
      privacy: 'Privacy Policy',
      deleteAccount: 'Delete Account',
    },
    lang: { en: 'EN', es: 'ES', he: 'HE' },

    // ── Landing ──────────────────────────────────────────────────────────────
    hero: {
      title: 'Tora Study',
      subtitle: 'Your companion for studying Torah, Mishnah and Talmud',
      tagline: 'Sacred texts. AI-powered tools. In your pocket.',
      download: 'Download on Google Play',
      downloadSoon: 'Coming soon on Google Play',
    },
    features: {
      title: 'Everything you need to study',
      groupLibrary: '📚 The Library',
      groupAI: '🤖 AI-Powered Study Tools',
      tanakh: {
        title: 'Tanakh',
        desc: 'The complete Hebrew Bible in Hebrew (with nikud), English (JPS 1917) and Spanish, with Rashi\'s classic commentary on every book.',
      },
      mishnah: {
        title: 'Mishnah',
        desc: 'All 63 tractates in Hebrew, Spanish and English — including Pirkei Avot as its own featured section.',
      },
      talmud: {
        title: 'Babylonian Talmud',
        desc: 'All 37 tractates of the Bavli, complete in Hebrew/Aramaic, Spanish and English, with Rashi\'s commentary alongside the text.',
      },
      tosefta: {
        title: 'Tosefta',
        desc: '61 tractates of this early tannaitic companion to the Mishnah, in Hebrew.',
      },
      midrash: {
        title: 'Midrash & Classic Commentaries',
        desc: 'Midrash Rabbah, Sifrei, Midrash Tanchuma, Mekhilta and Sifra — centuries of rabbinic interpretation, in Hebrew.',
      },
      prayer: {
        title: 'Prayer & Holidays',
        desc: 'The Passover Haggadah and the weekday Siddur, ready to read and follow along.',
      },
      audio: {
        title: 'Listen to Every Text',
        desc: 'Text-to-speech in Hebrew, Spanish and English — play a single verse or an entire chapter hands-free.',
      },
      search: {
        title: 'Search the Whole Library',
        desc: 'Full-text and semantic search across the entire collection — find the passage you\'re thinking of, even if you don\'t remember the exact words.',
      },
      multilang: {
        title: 'Multilingual',
        desc: 'Interface available in Spanish, English and Hebrew. Texts in their original languages with translations.',
      },
      chat: {
        title: 'AI Chat',
        desc: 'Ask questions and chat with an AI grounded in the text — every answer cites real verses, never invented content.',
      },
      quiz: {
        title: 'Auto-Generated Quizzes',
        desc: 'Test your understanding with AI-generated quizzes for any chapter, tractate or daf, with a saved history of your results.',
      },
      summary: {
        title: 'Instant Summaries',
        desc: 'Get a clear AI-generated summary of any chapter in seconds.',
      },
      guides: {
        title: 'Personalized Study Guides',
        desc: 'Pick any topic and let AI build a multi-lesson study guide grounded in real sources — complete with a final quiz and certificate of completion.',
      },
    },
    principles: {
      title: 'Our guiding principle',
      text: 'The sacred text is never generated by AI. All texts are sourced from real public-domain sources (Sefaria, Wikisource) and stored in our database. AI only powers study tools like chat, summaries and quizzes.',
    },
    download: {
      title: 'Available on Android',
      subtitle: 'Free to download. 50 credits included on sign-up.',
      google: 'Get it on Google Play',
    },
    contact: {
      title: 'Contact',
      text: 'Questions, feedback or support? Write to us at',
    },
    footer: {
      copyright: '© 2026 FAB Apps. All rights reserved.',
      contact: 'Contact',
      privacy: 'Privacy Policy',
      delete: 'Delete Account',
    },

    // ── Privacy ───────────────────────────────────────────────────────────────
    privacy: {
      title: 'Privacy Policy',
      updated: 'Last updated: June 27, 2026',
      intro: 'FAB Apps ("we", "us", or "our") operates the Tora Study mobile application (the "App"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our App and the choices you have associated with that data.',

      s1_title: '1. Information We Collect',
      s1_email: '<strong>Email address</strong> — collected during registration or via Google Sign-In. Used for authentication and account management.',
      s1_name: '<strong>Name and profile picture</strong> — obtained from Google OAuth when you sign in with Google. Used to personalize your profile.',
      s1_device: '<strong>Device ID</strong> — an anonymous identifier used to prevent abuse of the sign-up credit bonus.',
      s1_usage: '<strong>Usage data</strong> — queries sent to the AI (chat, quiz, summary). Stored transiently to generate responses; not sold or shared with third parties beyond the AI provider.',

      s2_title: '2. How We Use Your Information',
      s2_auth: 'Authentication and account management.',
      s2_credits: 'Managing your credit balance for AI features.',
      s2_ai: 'Generating AI-powered responses (chat, quiz, summary) via OpenAI.',
      s2_purchases: 'Processing in-app purchases via Google Play Billing and RevenueCat.',
      s2_improve: 'Improving and maintaining the App.',

      s3_title: '3. Third-Party Services',
      s3_intro: 'We use the following third-party services that may process your data:',
      s3_google: '<strong>Google OAuth / Google Play</strong> — for authentication and in-app purchases.',
      s3_openai: '<strong>OpenAI</strong> — to power AI features (chat, summaries, quizzes). Queries are sent to OpenAI\'s API under their <a href="https://openai.com/policies/privacy-policy" target="_blank" rel="noopener">Privacy Policy</a>.',
      s3_revenuecat: '<strong>RevenueCat</strong> — for managing and verifying in-app purchases.',

      s4_title: '4. Data Retention',
      s4_text: 'We retain your personal data for as long as your account is active. You may request deletion at any time (see Section 6). After deletion, we retain your email in an anonymized blocklist solely to prevent abuse of the sign-up bonus.',

      s5_title: '5. Data Security',
      s5_text: 'We use industry-standard measures to protect your data, including encrypted connections (HTTPS/TLS) and hashed passwords. No method of transmission over the Internet is 100% secure.',

      s6_title: '6. Your Rights — Account Deletion',
      s6_text: 'You have the right to request deletion of your account and all associated data at any time. You can delete your account directly from the App (Settings → Delete Account) or by emailing us at',
      s6_deleted: 'Upon deletion, we remove your email, name, picture, credit balance, transaction history, quiz sessions, reading plans and notes.',

      s7_title: '7. Children\'s Privacy',
      s7_text: 'The App is not directed to children under 13. We do not knowingly collect personal information from children under 13.',

      s8_title: '8. Changes to This Policy',
      s8_text: 'We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new policy on this page with an updated date.',

      s9_title: '9. Contact Us',
      s9_text: 'If you have questions about this Privacy Policy, please contact us at',
    },

    // ── Delete Account ────────────────────────────────────────────────────────
    delete: {
      title: 'Delete Your Account',
      subtitle: 'We\'re sorry to see you go. Here\'s how to permanently delete your account.',

      method1_title: 'Option 1 — Delete from the App (Instant)',
      method1_step1: 'Open the Tora Study app.',
      method1_step2: 'Go to your profile or settings.',
      method1_step3: 'Tap <strong>Delete Account</strong>.',
      method1_step4: 'Confirm the deletion.',
      method1_note: 'Your account and all data will be permanently deleted immediately.',

      method2_title: 'Option 2 — Email Us',
      method2_text: 'If you cannot access the app, send an email to',
      method2_subject: 'with the subject <strong>"Delete Account"</strong> from the email address associated with your account. We will process your request within 5 business days.',

      deleted_title: 'What data is deleted',
      deleted_account: 'Your email, name and profile picture',
      deleted_credits: 'Credit balance and transaction history',
      deleted_quiz: 'Quiz sessions and results',
      deleted_plans: 'Reading plans and notes',
      deleted_progress: 'Reading progress',

      retained_title: 'What we retain',
      retained_text: 'After deletion, your email is added to an anonymized blocklist to prevent abuse of the sign-up credit bonus. No other personal information is retained.',

      contact_title: 'Need help?',
      contact_text: 'For any questions about account deletion, write to us at',
    },
  },

  // ── ESPAÑOL ─────────────────────────────────────────────────────────────────
  es: {
    nav: {
      home: 'Inicio',
      privacy: 'Política de privacidad',
      deleteAccount: 'Eliminar cuenta',
    },
    lang: { en: 'EN', es: 'ES', he: 'HE' },

    hero: {
      title: 'Tora Study',
      subtitle: 'Tu compañero para el estudio de la Torá, Mishná y Talmud',
      tagline: 'Textos sagrados. Herramientas con IA. En tu bolsillo.',
      download: 'Descargar en Google Play',
      downloadSoon: 'Próximamente en Google Play',
    },
    features: {
      title: 'Todo lo que necesitás para estudiar',
      groupLibrary: '📚 La Biblioteca',
      groupAI: '🤖 Herramientas de estudio con IA',
      tanakh: {
        title: 'Tanaj',
        desc: 'La Biblia hebrea completa en hebreo (con nikud), inglés (JPS 1917) y español, con el comentario clásico de Rashi en cada libro.',
      },
      mishnah: {
        title: 'Mishná',
        desc: 'Los 63 tratados completos en hebreo, español e inglés — incluyendo Pirkei Avot como sección propia destacada.',
      },
      talmud: {
        title: 'Talmud Bavli',
        desc: 'Los 37 tratados completos del Bavli en hebreo/arameo, español e inglés, con el comentario de Rashi junto al texto.',
      },
      tosefta: {
        title: 'Tosefta',
        desc: '61 tratados de esta obra tannaítica temprana, complementaria a la Mishná, en hebreo.',
      },
      midrash: {
        title: 'Midrash y comentarios clásicos',
        desc: 'Midrash Rabbah, Sifrei, Midrash Tanchuma, Mekhilta y Sifra — siglos de interpretación rabínica, en hebreo.',
      },
      prayer: {
        title: 'Oración y festividades',
        desc: 'La Hagadá de Pésaj y el Sidur de días de semana, listos para leer y seguir.',
      },
      audio: {
        title: 'Escuchá cada texto',
        desc: 'Texto a voz en hebreo, español e inglés — reproducí un versículo o un capítulo completo con las manos libres.',
      },
      search: {
        title: 'Buscá en toda la biblioteca',
        desc: 'Búsqueda de texto completo y semántica en toda la colección — encontrá el pasaje que tenés en mente, aunque no recuerdes las palabras exactas.',
      },
      multilang: {
        title: 'Multilingüe',
        desc: 'Interfaz en español, inglés y hebreo. Textos en sus idiomas originales con traducciones.',
      },
      chat: {
        title: 'Chat con IA',
        desc: 'Hacé preguntas y chateá con una IA anclada en el texto — cada respuesta cita versículos reales, nunca contenido inventado.',
      },
      quiz: {
        title: 'Quizzes generados automáticamente',
        desc: 'Poné a prueba tu comprensión con quizzes generados por IA para cualquier capítulo, tratado o daf, con historial guardado de tus resultados.',
      },
      summary: {
        title: 'Resúmenes al instante',
        desc: 'Obtené un resumen claro generado por IA de cualquier capítulo en segundos.',
      },
      guides: {
        title: 'Guías de estudio personalizadas',
        desc: 'Elegí cualquier tema y dejá que la IA arme una guía de estudio de varias lecciones fundamentada en fuentes reales — con quiz final y certificado de finalización.',
      },
    },
    principles: {
      title: 'Nuestro principio rector',
      text: 'El texto sagrado nunca es generado por la IA. Todos los textos provienen de fuentes reales de dominio público (Sefaria, Wikisource) y se almacenan en nuestra base de datos. La IA solo impulsa herramientas de estudio como chat, resúmenes y quizzes.',
    },
    download: {
      title: 'Disponible en Android',
      subtitle: 'Descarga gratuita. 50 créditos incluidos al registrarte.',
      google: 'Obtenerlo en Google Play',
    },
    contact: {
      title: 'Contacto',
      text: '¿Preguntas, comentarios o soporte? Escribinos a',
    },
    footer: {
      copyright: '© 2026 FAB Apps. Todos los derechos reservados.',
      contact: 'Contacto',
      privacy: 'Política de privacidad',
      delete: 'Eliminar cuenta',
    },

    privacy: {
      title: 'Política de privacidad',
      updated: 'Última actualización: 27 de junio de 2026',
      intro: 'FAB Apps ("nosotros" o "nuestro") opera la aplicación móvil Tora Study ("la App"). Esta página informa sobre nuestras políticas de recopilación, uso y divulgación de datos personales cuando usás nuestra App.',

      s1_title: '1. Información que recopilamos',
      s1_email: '<strong>Dirección de email</strong> — recopilada durante el registro o mediante Google Sign-In. Se usa para autenticación y gestión de la cuenta.',
      s1_name: '<strong>Nombre e imagen de perfil</strong> — obtenidos de Google OAuth al iniciar sesión con Google. Se usan para personalizar tu perfil.',
      s1_device: '<strong>ID de dispositivo</strong> — un identificador anónimo para prevenir el abuso del bono de créditos de bienvenida.',
      s1_usage: '<strong>Datos de uso</strong> — consultas enviadas a la IA (chat, quiz, resumen). Se almacenan transitoriamente para generar respuestas; no se venden ni comparten con terceros más allá del proveedor de IA.',

      s2_title: '2. Cómo usamos tu información',
      s2_auth: 'Autenticación y gestión de cuenta.',
      s2_credits: 'Gestión de tu saldo de créditos para las funciones de IA.',
      s2_ai: 'Generación de respuestas impulsadas por IA (chat, quiz, resumen) mediante OpenAI.',
      s2_purchases: 'Procesamiento de compras en la app mediante Google Play Billing y RevenueCat.',
      s2_improve: 'Mejora y mantenimiento de la App.',

      s3_title: '3. Servicios de terceros',
      s3_intro: 'Utilizamos los siguientes servicios de terceros que pueden procesar tus datos:',
      s3_google: '<strong>Google OAuth / Google Play</strong> — para autenticación y compras en la app.',
      s3_openai: '<strong>OpenAI</strong> — para las funciones de IA. Las consultas se envían a la API de OpenAI bajo su <a href="https://openai.com/policies/privacy-policy" target="_blank" rel="noopener">Política de privacidad</a>.',
      s3_revenuecat: '<strong>RevenueCat</strong> — para gestionar y verificar las compras en la app.',

      s4_title: '4. Retención de datos',
      s4_text: 'Conservamos tus datos personales mientras tu cuenta esté activa. Podés solicitar la eliminación en cualquier momento (ver Sección 6). Tras la eliminación, conservamos tu email en una lista de bloqueo anonimizada únicamente para prevenir el abuso del bono de bienvenida.',

      s5_title: '5. Seguridad de los datos',
      s5_text: 'Utilizamos medidas estándar de la industria para proteger tus datos, incluyendo conexiones cifradas (HTTPS/TLS) y contraseñas hasheadas. Ningún método de transmisión por Internet es 100% seguro.',

      s6_title: '6. Tus derechos — Eliminación de cuenta',
      s6_text: 'Tenés derecho a solicitar la eliminación de tu cuenta y todos los datos asociados en cualquier momento. Podés eliminar tu cuenta directamente desde la App (Configuración → Eliminar cuenta) o enviándonos un email a',
      s6_deleted: 'Al eliminar la cuenta, borramos tu email, nombre, foto, saldo de créditos, historial de transacciones, sesiones de quiz, planes de lectura y notas.',

      s7_title: '7. Privacidad de menores',
      s7_text: 'La App no está dirigida a menores de 13 años. No recopilamos conscientemente información personal de menores de 13 años.',

      s8_title: '8. Cambios en esta política',
      s8_text: 'Podemos actualizar esta Política de privacidad periódicamente. Te notificaremos los cambios publicando la nueva política en esta página con una fecha actualizada.',

      s9_title: '9. Contacto',
      s9_text: 'Si tenés preguntas sobre esta Política de privacidad, contactanos en',
    },

    delete: {
      title: 'Eliminar tu cuenta',
      subtitle: 'Lamentamos verte partir. Así podés eliminar permanentemente tu cuenta.',

      method1_title: 'Opción 1 — Eliminar desde la App (instantáneo)',
      method1_step1: 'Abrí la app Tora Study.',
      method1_step2: 'Ir a tu perfil o configuración.',
      method1_step3: 'Tocá <strong>Eliminar cuenta</strong>.',
      method1_step4: 'Confirmá la eliminación.',
      method1_note: 'Tu cuenta y todos los datos se eliminarán de forma permanente e inmediata.',

      method2_title: 'Opción 2 — Envianos un email',
      method2_text: 'Si no podés acceder a la app, enviá un email a',
      method2_subject: 'con el asunto <strong>"Delete Account"</strong> desde la dirección de email asociada a tu cuenta. Procesaremos tu solicitud dentro de los 5 días hábiles.',

      deleted_title: 'Qué datos se eliminan',
      deleted_account: 'Tu email, nombre e imagen de perfil',
      deleted_credits: 'Saldo de créditos e historial de transacciones',
      deleted_quiz: 'Sesiones y resultados de quiz',
      deleted_plans: 'Planes de lectura y notas',
      deleted_progress: 'Progreso de lectura',

      retained_title: 'Qué conservamos',
      retained_text: 'Tras la eliminación, tu email se agrega a una lista de bloqueo anonimizada para prevenir el abuso del bono de bienvenida. No se conserva ninguna otra información personal.',

      contact_title: '¿Necesitás ayuda?',
      contact_text: 'Para cualquier consulta sobre la eliminación de cuenta, escribinos a',
    },
  },

  // ── עברית ────────────────────────────────────────────────────────────────────
  he: {
    nav: {
      home: 'בית',
      privacy: 'מדיניות פרטיות',
      deleteAccount: 'מחיקת חשבון',
    },
    lang: { en: 'EN', es: 'ES', he: 'HE' },

    hero: {
      title: 'תורה Study',
      subtitle: 'המלווה שלך ללימוד תורה, משנה ותלמוד',
      tagline: 'טקסטים קדושים. כלי בינה מלאכותית. בכיסך.',
      download: 'הורד ב-Google Play',
      downloadSoon: 'בקרוב ב-Google Play',
    },
    features: {
      title: 'כל מה שצריך ללימוד',
      groupLibrary: '📚 הספרייה',
      groupAI: '🤖 כלי לימוד מבוססי בינה מלאכותית',
      tanakh: {
        title: 'תנ״ך',
        desc: 'התנ״ך השלם בעברית (עם ניקוד), אנגלית (JPS 1917) וספרדית, עם פירוש רש״י הקלאסי על כל ספר.',
      },
      mishnah: {
        title: 'משנה',
        desc: 'כל 63 המסכתות בעברית, ספרדית ואנגלית — כולל פרקי אבות כקטע מומלץ בפני עצמו.',
      },
      talmud: {
        title: 'תלמוד בבלי',
        desc: 'כל 37 מסכתות הבבלי, שלמות בעברית/ארמית, ספרדית ואנגלית, עם פירוש רש״י לצד הטקסט.',
      },
      tosefta: {
        title: 'תוספתא',
        desc: '61 מסכתות של חיבור תנאי מוקדם זה, המשלים את המשנה, בעברית.',
      },
      midrash: {
        title: 'מדרש ופרשנות קלאסית',
        desc: 'מדרש רבה, ספרי, מדרש תנחומא, מכילתא וספרא — מאות שנות פרשנות רבנית, בעברית.',
      },
      prayer: {
        title: 'תפילה וחגים',
        desc: 'הגדה של פסח וסידור לימי חול, מוכנים לקריאה ולמעקב.',
      },
      audio: {
        title: 'האזן לכל טקסט',
        desc: 'טקסט לדיבור בעברית, ספרדית ואנגלית — הפעל פסוק בודד או פרק שלם בלי להשתמש בידיים.',
      },
      search: {
        title: 'חפש בכל הספרייה',
        desc: 'חיפוש טקסט מלא וסמנטי בכל האוסף — מצא את הקטע שאתה חושב עליו, גם אם אינך זוכר את המילים המדויקות.',
      },
      multilang: {
        title: 'רב-לשוני',
        desc: 'ממשק בספרדית, אנגלית ועברית. טקסטים בשפות המקוריות שלהם עם תרגומים.',
      },
      chat: {
        title: 'צ׳אט עם בינה מלאכותית',
        desc: 'שאל שאלות ושוחח עם בינה מלאכותית המבוססת על הטקסט — כל תשובה מצטטת פסוקים אמיתיים, לעולם לא תוכן מומצא.',
      },
      quiz: {
        title: 'חידונים אוטומטיים',
        desc: 'בחן את ההבנה שלך עם חידונים שנוצרו על ידי בינה מלאכותית לכל פרק, מסכת או דף, עם היסטוריה שמורה של התוצאות שלך.',
      },
      summary: {
        title: 'סיכומים מיידיים',
        desc: 'קבל סיכום ברור שנוצר על ידי בינה מלאכותית לכל פרק תוך שניות.',
      },
      guides: {
        title: 'מדריכי לימוד מותאמים אישית',
        desc: 'בחר כל נושא ותן לבינה המלאכותית לבנות מדריך לימוד רב-שיעורי המבוסס על מקורות אמיתיים — כולל חידון מסכם ותעודת סיום.',
      },
    },
    principles: {
      title: 'העיקרון המנחה שלנו',
      text: 'הטקסט הקדוש לעולם אינו נוצר על ידי בינה מלאכותית. כל הטקסטים לקוחים ממקורות אמיתיים בנחלת הכלל (Sefaria, Wikisource) ומאוחסנים במסד הנתונים שלנו. הבינה המלאכותית מפעילה רק כלי לימוד כמו צ׳אט, סיכומים וחידונים.',
    },
    download: {
      title: 'זמין ב-Android',
      subtitle: 'הורדה חינמית. 50 קרדיטים כלולים בהרשמה.',
      google: 'הורד ב-Google Play',
    },
    contact: {
      title: 'צור קשר',
      text: 'שאלות, משוב או תמיכה? כתוב אלינו ל',
    },
    footer: {
      copyright: '© 2026 FAB Apps. כל הזכויות שמורות.',
      contact: 'צור קשר',
      privacy: 'מדיניות פרטיות',
      delete: 'מחיקת חשבון',
    },

    privacy: {
      title: 'מדיניות פרטיות',
      updated: 'עודכן לאחרונה: 27 ביוני 2026',
      intro: 'FAB Apps ("אנחנו" או "שלנו") מפעילה את אפליקציית המובייל תורה Study ("האפליקציה"). דף זה מודיע על מדיניותנו בנוגע לאיסוף, שימוש וחשיפה של נתונים אישיים בעת השימוש באפליקציה.',

      s1_title: '1. מידע שאנו אוספים',
      s1_email: '<strong>כתובת אימייל</strong> — נאספת בעת הרישום או דרך Google Sign-In. משמשת לאימות וניהול החשבון.',
      s1_name: '<strong>שם ותמונת פרופיל</strong> — מתקבלים מ-Google OAuth בכניסה עם Google. משמשים להתאמה אישית של הפרופיל.',
      s1_device: '<strong>מזהה מכשיר</strong> — מזהה אנונימי למניעת שימוש לרעה בבונוס קרדיטים ההרשמה.',
      s1_usage: '<strong>נתוני שימוש</strong> — שאילתות שנשלחו לבינה המלאכותית (צ׳אט, חידון, סיכום). מאוחסנות באופן זמני ליצירת תשובות; אינן נמכרות או משותפות עם צדדים שלישיים מעבר לספק הבינה המלאכותית.',

      s2_title: '2. כיצד אנו משתמשים במידע שלך',
      s2_auth: 'אימות וניהול חשבון.',
      s2_credits: 'ניהול יתרת הקרדיטים שלך לתכונות הבינה המלאכותית.',
      s2_ai: 'יצירת תשובות מונעות בינה מלאכותית (צ׳אט, חידון, סיכום) דרך OpenAI.',
      s2_purchases: 'עיבוד רכישות בתוך האפליקציה דרך Google Play Billing ו-RevenueCat.',
      s2_improve: 'שיפור ותחזוקת האפליקציה.',

      s3_title: '3. שירותי צד שלישי',
      s3_intro: 'אנו משתמשים בשירותי צד שלישי הבאים שעשויים לעבד את הנתונים שלך:',
      s3_google: '<strong>Google OAuth / Google Play</strong> — לאימות ורכישות בתוך האפליקציה.',
      s3_openai: '<strong>OpenAI</strong> — לתכונות הבינה המלאכותית תחת <a href="https://openai.com/policies/privacy-policy" target="_blank" rel="noopener">מדיניות הפרטיות שלהם</a>.',
      s3_revenuecat: '<strong>RevenueCat</strong> — לניהול ואימות רכישות בתוך האפליקציה.',

      s4_title: '4. שמירת נתונים',
      s4_text: 'אנו שומרים את הנתונים האישיים שלך כל עוד חשבונך פעיל. ניתן לבקש מחיקה בכל עת (ראה סעיף 6). לאחר המחיקה, שומרים את האימייל שלך ברשימת חסימה אנונימית אך ורק למניעת שימוש לרעה בבונוס ההרשמה.',

      s5_title: '5. אבטחת נתונים',
      s5_text: 'אנו משתמשים באמצעים סטנדרטיים בתעשייה להגנה על הנתונים שלך, כולל חיבורים מוצפנים (HTTPS/TLS) וסיסמאות מגובבות.',

      s6_title: '6. הזכויות שלך — מחיקת חשבון',
      s6_text: 'יש לך זכות לבקש מחיקת חשבונך וכל הנתונים המשויכים בכל עת. ניתן למחוק את החשבון ישירות מהאפליקציה או לשלוח אימייל ל',
      s6_deleted: 'עם המחיקה, מסירים את האימייל, השם, התמונה, יתרת הקרדיטים, היסטוריית העסקאות, חידונים, תוכניות קריאה והערות.',

      s7_title: '7. פרטיות ילדים',
      s7_text: 'האפליקציה אינה מיועדת לילדים מתחת לגיל 13. אין אנו אוספים מידע אישי מילדים מתחת לגיל 13.',

      s8_title: '8. שינויים במדיניות זו',
      s8_text: 'אנו עשויים לעדכן את מדיניות הפרטיות מעת לעת. נודיע על שינויים על ידי פרסום המדיניות החדשה בדף זה עם תאריך מעודכן.',

      s9_title: '9. צור קשר',
      s9_text: 'אם יש לך שאלות בנוגע למדיניות פרטיות זו, צור קשר ב',
    },

    delete: {
      title: 'מחיקת החשבון שלך',
      subtitle: 'כיצד למחוק את החשבון שלך לצמיתות.',

      method1_title: 'אפשרות 1 — מחיקה מהאפליקציה (מיידי)',
      method1_step1: 'פתח את אפליקציית תורה Study.',
      method1_step2: 'עבור לפרופיל שלך או להגדרות.',
      method1_step3: 'הקש על <strong>מחק חשבון</strong>.',
      method1_step4: 'אשר את המחיקה.',
      method1_note: 'החשבון וכל הנתונים יימחקו לצמיתות ומיידית.',

      method2_title: 'אפשרות 2 — שלח לנו אימייל',
      method2_text: 'אם אינך יכול לגשת לאפליקציה, שלח אימייל ל',
      method2_subject: 'עם הנושא <strong>"Delete Account"</strong> מכתובת האימייל המשויכת לחשבונך. נטפל בבקשתך תוך 5 ימי עסקים.',

      deleted_title: 'אילו נתונים נמחקים',
      deleted_account: 'האימייל, השם ותמונת הפרופיל שלך',
      deleted_credits: 'יתרת קרדיטים והיסטוריית עסקאות',
      deleted_quiz: 'חידונים ותוצאות',
      deleted_plans: 'תוכניות קריאה והערות',
      deleted_progress: 'התקדמות קריאה',

      retained_title: 'מה אנו שומרים',
      retained_text: 'לאחר המחיקה, האימייל שלך נוסף לרשימת חסימה אנונימית למניעת שימוש לרעה בבונוס ההרשמה. לא נשמר שום מידע אישי אחר.',

      contact_title: 'זקוק לעזרה?',
      contact_text: 'לכל שאלה בנוגע למחיקת חשבון, כתוב אלינו ל',
    },
  },
};

// ── Core i18n engine ─────────────────────────────────────────────────────────

const CONTACT_EMAIL = 'feedback@fab-apps.com';
const SUPPORTED = ['en', 'es', 'he'];

function detectLang() {
  const stored = localStorage.getItem('tora_lang');
  if (stored && SUPPORTED.includes(stored)) return stored;
  const prefs = Array.from(navigator.languages || [navigator.language || 'en']);
  for (const raw of prefs) {
    const code = raw.slice(0, 2).toLowerCase();
    if (SUPPORTED.includes(code)) return code;
  }
  return 'en';
}

function setLang(lang) {
  localStorage.setItem('tora_lang', lang);
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === 'he' ? 'rtl' : 'ltr';

  const t = TRANSLATIONS[lang];
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.getAttribute('data-i18n');
    const val = key.split('.').reduce((o, k) => o?.[k], t);
    if (val !== undefined) {
      if (el.hasAttribute('data-i18n-html')) {
        el.innerHTML = val;
      } else {
        el.textContent = val;
      }
    }
  });

  // Email links
  document.querySelectorAll('[data-i18n-email]').forEach((el) => {
    el.textContent = CONTACT_EMAIL;
    el.href = `mailto:${CONTACT_EMAIL}`;
  });

  // Active lang button
  document.querySelectorAll('.lang-btn').forEach((btn) => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });

  // Page title
  const titles = { en: 'Tora Study', es: 'Tora Study', he: 'תורה Study' };
  const pageTitle = document.querySelector('title');
  if (pageTitle) {
    const suffix = pageTitle.dataset.titleSuffix;
    pageTitle.textContent = suffix ? `${titles[lang]} — ${suffix}` : titles[lang];
  }
}

function initI18n() {
  const lang = detectLang();

  document.querySelectorAll('.lang-btn').forEach((btn) => {
    btn.addEventListener('click', () => setLang(btn.dataset.lang));
  });

  setLang(lang);
}

document.addEventListener('DOMContentLoaded', initI18n);
